parameters:
    leapt_elastica.indexes: []
    leapt_elastica.config: []

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Leapt\ElasticaBundle\Command\:
        resource: '../../Command/*'

    Leapt\ElasticaBundle\Service:
        arguments:
            $namespace: "%leapt_elastica.namespace%"
        calls:
            - [ setContainer, [ "@service_container" ]]
            - [ setIndexes, [ "%leapt_elastica.indexes%" ]]

    Leapt\ElasticaBundle\ServiceInterface: "@Leapt\\ElasticaBundle\\Service"

    Leapt\ElasticaBundle\Client:
        arguments:
            - "%leapt_elastica.config%"
        calls:
            - [ setLogger, [ "@Leapt\\ElasticaBundle\\Logger\\ElasticaLogger" ]]

    Leapt\ElasticaBundle\Listener\IndexSubscriber:
        tags:
            - { name: doctrine.event_subscriber }

    Leapt\ElasticaBundle\Logger\ElasticaLogger:
        arguments:
            - "@logger"
            - "%kernel.debug%"
        tags:
            - { name: monolog.logger, channel: elastica }

    Leapt\ElasticaBundle\DataCollector\ElasticaDataCollector:
        tags:
            - { name: data_collector, template: "@LeaptElastica/Collector/elastica.html.twig", id: "elastica" }